// <auto-generated />
using Amazon.Models.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Amazon.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220511210216_updatecommentd")]
    partial class updatecommentd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Amazon.Models.Tables.A_Comment", b =>
                {
                    b.Property<int>("A_Comment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("A_Comment_Product_id")
                        .HasColumnType("int");

                    b.Property<int>("A_Comment_user_id")
                        .HasColumnType("int");

                    b.Property<string>("A_Comments")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("A_Comment_id");

                    b.ToTable("comments");
                });

            modelBuilder.Entity("Amazon.Models.Tables.A_Pincode", b =>
                {
                    b.Property<int>("A_UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("A_Area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("A_City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("A_Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("A_District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("A_Isactive")
                        .HasColumnType("int");

                    b.Property<string>("A_Iso2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("A_Phone_code")
                        .HasColumnType("int");

                    b.Property<string>("A_State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("A_Zipcode")
                        .HasColumnType("int");

                    b.HasKey("A_UID");

                    b.ToTable("pincodes");
                });

            modelBuilder.Entity("Amazon.Models.Tables.A_Products", b =>
                {
                    b.Property<int>("A_Product_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("A_About")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("A_Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("A_Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("A_Model_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("A_Price")
                        .HasColumnType("float");

                    b.Property<string>("A_Product_dimensions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("A_Product_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("A_Product_specification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("A_Product_url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("A_Product_weight")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("A_Quantity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("A_Tech_details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("A_Total_like")
                        .HasColumnType("int");

                    b.Property<int>("A_Total_view")
                        .HasColumnType("int");

                    b.Property<string>("A_Varient")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("A_Product_id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Amazon.Models.Tables.A_Review", b =>
                {
                    b.Property<int>("A_Review_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("A_Like")
                        .HasColumnType("int");

                    b.Property<int>("A_Review_product_id")
                        .HasColumnType("int");

                    b.Property<int>("A_Review_user_id")
                        .HasColumnType("int");

                    b.Property<int>("A_View")
                        .HasColumnType("int");

                    b.HasKey("A_Review_id");

                    b.ToTable("reviews");
                });

            modelBuilder.Entity("Amazon.Models.Tables.A_Users", b =>
                {
                    b.Property<int>("A_User_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("A_Created")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("A_Email_add")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("A_Isactive")
                        .HasColumnType("int");

                    b.Property<string>("A_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("A_Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("A_Phone_number")
                        .HasColumnType("bigint");

                    b.HasKey("A_User_id");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
