// <auto-generated />
using Amazon.Models.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Amazon.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Amazon.Models.Tables.A_Users", b =>
                {
                    b.Property<int>("A_User_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("A_Email_add")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("A_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("A_Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("A_User_id");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
